name: admin
http-port: :8080
runmode: dev
table-prefix: gab_
db:
- name: default
  driver: mysql
  dsn: root:root@tcp(localhost:3306)/lwx_backend_go?charset=utf8mb4
  log: runtime/log/mysql/default.log
  max-idle-conn: 5
  max-open-conns: 30
  show-sql: true