name: admin
http-port: 8080
runmode: dev
table-prefix: admin_
db:
  - name: default
    driver: mysql
    dsn: lwx:jsptpd@tcp(218.94.126.251:3306)/lwx_admin_go?charset=utf8mb4,utf8
    log: runtime/log/mysql/default.log
    max-idle-conn: 5
    max-open-conns: 30